---
- name: Set OSPF configuration
  ios_config:
    timeout: 30
    lines:
      - router-id 3.3.3.3
      - netw 23.23.23.0 0.0.0.255 area 0
      - netw 3.3.3.0 0.0.0.255 area 0
      - netw 192.168.122.0 0.0.0.255 area 0
    parents: router ospf 1