---
- name: Set OSPF configuration
  ios_config:
    timeout: 30
    provider: "{{provider}}"
    lines:
      - router-id 1.1.1.1
      - netw 1.1.1.0 0.0.0.255 area 0
      - netw 12.12.12.0 0.0.0.255 area 0
      - netw 192.168.122.0 0.0.0.255 area 0
    parents: router ospf 1