---
- name: config
  hosts: R1
  connection: local
  gather_facts: no
  tasks:
    - name: configure top level configuration
      ios_config:
        lines: hostname {{ inventory_hostname }}
        timeout: 30

    - name: interface IP address
      ios_config:
        timeout: 30
        provider: 
          username: cisco
          password: cisco
        lines:
          - ip address 192.168.1.10 255.255.255.0
          - no shutdown
          - full-duplex
        parents: interface FastEthernet 1/0