---
- name: config
  hosts: R1
  connection: local
  gather_facts: no
  tasks:
    - name: configure top level configuration
      ios_config:
        provider: "{{provider}}"
        lines: hostname {{ inventory_hostname }}
        timeout: 30

    - name: interface IP address
      ios_config:
        provider: "{{provider}}"
        timeout: 30
        lines:
          - ip address 1.1.1.1 255.255.255.0
          - no shutdown
          - full-duplex
        parents: interface FastEthernet 0/1

    - name: interface IP address
      ios_config:
        provider: "{{provider}}"
        timeout: 30
        lines:
          - ip address 12.12.12.1 255.255.255.0
          - no shutdown
          - full-duplex
        parents: interface FastEthernet 2/0
        
  roles:
  - role: creds
  - role: r1_ospf