---
- name: config
  hosts: R3
  connection: local
  gather_facts: no
  tasks:

    - name: configure top level configuration
      ios_config:
        lines: hostname {{ inventory_hostname }}
        timeout: 30
        provider: "{{provider}}"

    - name: interface IP address
      ios_config:
        timeout: 30
        provider: "{{provider}}"
        lines:
          - ip address 3.3.3.3 255.255.255.0
          - no shutdown
          - full-duplex
        parents: interface FastEthernet 0/1

    - name: interface IP address
      ios_config:
        timeout: 30
        provider: "{{provider}}"
        lines:
          - ip address 23.23.23.3 255.255.255.0
          - no shutdown
          - full-duplex
        parents: interface FastEthernet 2/0

  roles:
  - role: r3_ospf