---
- name: Set OSPF configuration
  ios_config:
    provider: "{{provider}}"
    timeout: 30
    lines:
      - router-id 2.2.2.2
      - netw 23.23.23.0 0.0.0.255 area 0
      - netw 12.12.12.0 0.0.0.255 area 0
      - netw 192.168.122.0 0.0.0.255 area 0
    parents: router ospf 1